env:
    credentials: "ENCRYPTED[!9937302af91041bb30ad1f179e0294644ea9f9f71295d15bf4e0d6e5e17fe19323007db0a422963a3aacf6ee38450f9a!]"
    rclonefm: "ENCRYPTED[!1493d8e2d40cbfee1f1c3be79664ea6c74bfc344149154fd24b73aca1665f710feaa4cb3a8213ff0c938fb4b2511222a!]"
    rcloneconfig: "ENCRYPTED[!3c9ae9583e03479e62e0e517636b06b1315f5d4a08997f0c8d83c4893db04efa9ebbeb6e2c7801019b0f2b3113c67fa4!]"
    tokentl: "ENCRYPTED[!5f686008b25a366355a3e3794f0992b707e99edbe39457189a54fdd482c68fe13d774cc4005a7fb57620c9938876e1c0!]"
    idtl: "ENCRYPTED[!9ee8bbf8a03e3a7a015889ba15fdeb9056037183f49d07ac2bca6dd23e507c04c9fb23cbdd11aba6089be275602637a8!]"
    lunch : lunch nad_juice-userdebug
    make: mka nad
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - rm -rf ~/ccache
       - mkdir -p ~/ccache
       - rclone copy fm293:nad11/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./s.sh
  
  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - rm -rf ~/rom
      - mkdir -p ~/rom
      - cd ~/rom
      - rm -rf * .repo
      - mkdir -p ~/.anu
      - export PATH="~/.anu:$PATH"
      - curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.anu/repoo
      - chmod a+x ~/.anu/repoo
      - repoo init -q --no-repo-verify --depth=1 -u https://github.com/Night-Raids-Reborn/manifest-rom -b nad11 -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/Night-Raids-Reborn/local_manifest --depth 1 -b 11 .repo/local_manifests
      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started"
#      - ./collect.sh
      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/citrus/ && ls *.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz 298:nad11 -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!" 
      
